apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: thanos
  version: 12.0.3
  repo: https://argadepp.github.io/helm-chart
  valuesFile: https://raw.githubusercontent.com/argadepp/DevOps-Infra/master/Kubernetes/HelmCharts/thanos/thanos-values.yaml
  releaseName: thanos-app
  ## IF needed
  includeCRDs: true