apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: thanos
  version: 12.0.3
  repo: https://argadepp.github.io/helm-chart
  valuesFile: values.yaml
  releaseName: thanos-app
  ## IF needed
  includeCRDs: true