apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist-app
  namespace: utilities
spec:
  destination:
    namespace: utilities
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-docker
    repoURL: https://github.com/argadepp/gitops-examples-argocd
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
