---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calc
  name: calc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calc
  strategy: {}
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - image: 9673483686/calc:test2
        name: calc

